CREATE TABLE USERS
(	email	 VARCHAR(100)	NOT NULL,
	name	VARCHAR(30)	NOT NULL,
	password	VARCHAR(30)	NOT NULL,
	gender		VARCHAR(4),
	favcol	VARCHAR(10),
CONSTRAINT USERS_PK PRIMARY KEY (EMAIL));


INSERT INTO USERS (EMAIL, NAME, PASSWORD, GENDER, FAVOURITECOLOR)
VALUES ('BAD@gmail.com', 'Jess', 'password', 'F', 'Blue');